### ISSUE TITLE
S2-HU - 01 Registrar informacion nuevo paciente

### ISSUE THREAD

**Issue by Jean9310** [Jean9310/Caso-Hospital#10]

**Comment by AndresVel8** [comment]
Front: se hace un diseño premilinar de ingreso de datos del paciente
Back:
Base:

**Comment by Jean9310** [comment]
realización de pruebas  de la creación de clientes

**Comment by AndresVel8** [comment]
Se realiza el front de los abel para registrar la base de datos y se conceta con el repositorio
