### ISSUE TITLE
S1-Pruebas CRUD base de datos

### ISSUE THREAD

**Issue by Jean9310** [Jean9310/Caso-Hospital#8]

**Comment by Jean9310** [comment]
se hacen pruebas para que conectara con la base de datos

**Comment by AndresVel8** [comment]
back: Se realiza la prueba de agregar, quepa pendiente la prueba de buscar el dato agregado

**Comment by Jean9310** [comment]
se completan los repositorios de Auxiliar, Medico, Enfermero y Paciente
